Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/home/xxc/文档/workspace/sshtunnel/socksService.py", line 80, in handle
    self.handle_socks5(recv)
  File "/home/xxc/文档/workspace/sshtunnel/socksService.py", line 155, in handle_socks5
    atype)
  File "/home/xxc/文档/workspace/sshtunnel/socksService.py", line 43, in get_socks5_connect_socket
    return self.server.socks.connect_handle(dst,src,dst_type)
  File "/home/xxc/文档/workspace/sshtunnel/socksService.py", line 244, in connect_handle
    class SocksServer(SocketServer.TCPServer):
  File "/home/xxc/文档/workspace/sshtunnel/socksService.py", line 236, in get_socket
    
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 647, in open_channel
    raise e
ChannelException: (1, 'Administratively prohibited')


Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/home/xxc/文档/workspace/sshtunnel/socksService.py", line 80, in handle
    self.handle_socks5(recv)
  File "/home/xxc/文档/workspace/sshtunnel/socksService.py", line 155, in handle_socks5
    atype)
  File "/home/xxc/文档/workspace/sshtunnel/socksService.py", line 43, in get_socks5_connect_socket
    return self.server.socks.connect_handle(dst,src,dst_type)
  File "/home/xxc/文档/workspace/sshtunnel/socksService.py", line 240, in connect_handle
    socket=self.get_socket(self.old_conversation, dst, src)
  File "/home/xxc/文档/workspace/sshtunnel/socksService.py", line 233, in get_socket
    res=trans.open_channel('direct-tcpip', dst, src)
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 647, in open_channel
    raise e
ChannelException: (2, 'Connect failed')


